return {
	c = { "clang-format" },
	cpp = { "clang-format" },
	css = { "prettierd", "prettier" },
	go = { "goimports", "gofmt" },
	html = { "prettierd", "prettier" },
	java = { "google-java-format" },
	javascript = { "prettierd", "prettier" },
	json = { "prettierd", "prettier" },
	lua = { "stylua" },
	markdown = { "prettierd", "prettier" },
	python = { "isort", "black" },
	rust = { "rustfmt" },
	sql = { "sqlfmt" },
	typescript = { "prettierd", "prettier" },
	typescriptreact = { "prettierd", "prettier" },
	yaml = { "prettierd", "prettier" },
}
