return {
	c = { "cpplint" },
	cpp = { "cpplint" },
	css = { "stylelint" },
	go = { "golangci_lint" },
	html = { "htmlhint" },
	java = { "checkstyle" },
	javascript = { "eslint_d" },
	javascriptreact = { "eslint_d" },
	json = { "jsonlint" },
	lua = { "luacheck" },
	markdown = { "markdownlint" },
	rust = { "clippy" },
	sql = { "sqlfluff" },
	python = { "ruff" },
	typescript = { "eslint_d" },
	typescriptreact = { "eslint_d" },
	yaml = { "yamllint" },
}
